### ISSUE TITLE
Not working in my IDE

### ISSUE THREAD

**Issue by wildernessfamily** [Gordarg/bingo-kanban-vsc#1]
Hi, I was looking for a Kanban board inside VSCode. I saw your extension and thought I'd check it out. I installed within the VSCode Entension window. However, it dosn't seem to be working. After installing, there are no commands in the pallet. I searched for:
`bingo-kanban.add`
`bingo-kanban.board`
`bingo`

Not sure if I did something wrong or if there is a bug. Any guidance would be greatly apprecaited.

Macbook Pro macOS Monterey 12.7.1

Bingo Kanban: v0.0.2

VSCode
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

**Comment by tayyebi** [comment]
Dear @wildernessfamily,

Before everything, sorry for my late reply, please kindly note that you can run commands only on editing files.

Please check out the demo video.

![Visual Studio Code Kanban](https://raw.githubusercontent.com/Gordarg/bingo-kanban-vsc/main/demo.gif)

Let me know if it works for you.

Cheers.

**Comment by wildernessfamily** [comment]
@tayyebi Thanks for the reply.
That makes total sense :)
I look forward to giving this a try this weekend. :)
